export const SET_LOCATION = "SET_LOCATION";
export const CLEAR_LOCATION = "CLEAR_LOCATION";
export const SET_WEATHER_DATA = "SET_WEATHER_DATA";
export const SET_WEATHER_FORECAST = "SET_WEATHER_FORECAST";
export const CLEAR_WEATHER_DATA = "CLEAR_WEATHER_DATA";
export const CLEAR_WEATHER_FORECAST = "CLEAR_WEATHER_FORECAST";